# Copied from Twilight's Lint workflow.
#
# https://github.com/twilight-rs/twilight/blob/trunk/.github/workflows/lint.yml
name: Lint

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --workspace --tests

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
