name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'

env:
  minrust: 1.85

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        name:
          - stable
          - beta
          - nightly
          - macOS
          - Windows

        include:
          - name: beta
            toolchain: beta
          - name: nightly
            toolchain: nightly
          - name: macOS
            os: macOS-latest
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain || 'stable' }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build all features
        if: matrix.features == ''
        run: cargo build --all-features

      - name: Test all features (other)
        if: matrix.features == '' && runner.os != 'Linux'
        run: cargo test --all-features -- --skip set_deadline_policy

      - name: Test all features (Linux)
        if: matrix.features == '' && runner.os == 'Linux'
        run: sudo -E /home/runner/.cargo/bin/cargo test --all-features
#        run: sudo -E /usr/share/rust/.cargo/bin/cargo test --all-features

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - run: cargo clippy

  MSRV:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain (${{ env.minrust }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.minrust }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - run: cargo check --all-features

  doc:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: |
          cargo doc
